-- Nombre de la base de datos:
USE Planify_PIA;

-- Tabla a usar:
CREATE TABLE TAREAS_CARD (
	TAREA_ID INT PRIMARY KEY AUTO_INCREMENT
    , CATEGORIA VARCHAR(50) NOT NULL
    , ESTATUS INT NOT NULL
    , TITULO VARCHAR(50) NOT NULL
    , DESCRIPCION VARCHAR(250)
    , FECHA_INICIO DATETIME NOT NULL
    , FECHA_LIMITE DATETIME NOT NULL
)