# Generated by Django 5.1.3 on 2024-11-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('TAREA_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ESTATUS', models.IntegerField(choices=[(1, 'Vigente'), (0, 'Finalizada')])),
                ('TITULO', models.CharField(max_length=50)),
                ('DESCRIPCION', models.CharField(blank=True, max_length=250, null=True)),
                ('FECHA_INICIO', models.DateTimeField(auto_now_add=True)),
                ('FECHA_LIMITE', models.DateTimeField()),
            ],
            options={
                'db_table': 'TAREAS_CARD',
            },
        ),
    ]
