# Generated by Django 5.1.3 on 2024-11-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ESTATUS',
            field=models.IntegerField(choices=[(1, 'Vigente'), (0, 'Finalizada')], default=1),
        ),
    ]
